deploy backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -227,21 +227,28 @@ jobs:
       - run:
          name: Add back-end ip to ansible inventory
          command: |
+            echo "Fetching backend IP..."
+             # Use set -e to exit script if AWS command fails
+            set -e
             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --output text)
-         
 
-           
+            # Check if the IP variable is empty
+            if [ -z "${BACKEND_PUBLIC_IP}" ]; then
+              echo "Error: Failed to retrieve backend IP address."
+              exit 1
+            fi
+            echo "Backend IP Found: ${BACKEND_PUBLIC_IP}"
+
             mkdir -p .circleci/ansible
-            
             echo "[backend]" > .circleci/ansible/inventory.txt
-            
-            echo "${BACKEND_PUBLIC_IP} ansible_user=ubuntu" >> .circleci/ansible/inventory.txt 
+            echo "${BACKEND_PUBLIC_IP} ansible_user=ubuntu" >> .circleci/ansible/inventory.txt
+
             echo "--- Generated Inventory ---"
             cat .circleci/ansible/inventory.txt
-            echo "-------------------------"
+            echo "---------------------------"
 
       - persist_to_workspace:
           root: ~/ # This root is fine
@@ -404,7 +411,7 @@ jobs:
 
             cd .circleci/ansible
             cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml
+            ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml
 
       - destroy-environment
       - revert-migrations
