smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -501,47 +501,48 @@ jobs:
       - destroy-environment
       - revert-migrations
 
-# From input_file_1.png (separate steps/jobs)
-    #  - destroy-environment
-    #  - revert-migrations
-  # smoke-test:
-  #    docker:
-  #      - image: cimg/base:stable
-  #    steps:
-  #     - checkout
-  #     - install_awscli
-  #     - install_nodejs
-  #     - run:
-  #         name: Backend smoke test.
-  #         command: |
-  #           BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-  #           --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-  #           --query 'Reservations[*].Instances[*].PublicIpAddress' \
-  #           --output text)
 
-  #           export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+  smoke-test:
+     docker:
+       - image: cimg/base:stable
+     steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - run:
+          name: Backend smoke test.
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text)
 
-  #           if curl -sf $API_URL/api/status | grep -q "ok"
-  #           then
-  #           echo "Backend smoke test passed."
-  #           exit 0
-  #           else
-  #           echo "Backend smoke test failed."
-  #           exit 1
-  #           fi
-  #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
 
-  #           if curl -sf $FRONTEND_WEBSITE | grep -q "Welcome"
-  #           then
-  #           echo "Frontend smoke test passed."
-  #           exit 0
-  #           else
-  #           echo "Frontend smoke test failed."
-  #           exit 1
-  #           fi
+            if curl -sf $API_URL/api/status | grep -q "ok"
+            then
+            echo "Backend smoke test passed."
+            exit 0
+            else
+            echo "Backend smoke test failed."
+            exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+
+            if curl -sf $FRONTEND_WEBSITE | grep -q "Welcome"
+            then
+            echo "Frontend smoke test passed."
+            exit 0
+            else
+            echo "Frontend smoke test failed."
+            exit 1
+       
+            fi
+      - destroy-environment
+      - revert-migrations
 
 #   cloudfront-update:
 #     docker:
@@ -587,8 +588,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
